/*TRN_USUARIOS
*/
CREATE TABLE TRN_USUARIOS (
ID 						INT 			NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE 					VARCHAR(50) 	NOT NULL,
APELLIDOS 				VARCHAR(50) 	NOT NULL,
FECHA_DE_NACIMIENTO 	DATE 			NOT NULL,
EMAIL 					VARCHAR(50) 	NOT NULL UNIQUE,
PASSWORD				VARCHAR(50) 	NOT NULL
);
INSERT INTO TRN_USUARIOS (NOMBRE,APELLIDOS,FECHA_DE_NACIMIENTO,EMAIL)VALUES("ADMIN","ADMINIS",STR_TO_DATE("19/10/1990",'%d/%m/%Y'),"admin@trn.com",MD5("admin"));

/*TRN_PERFILES
*/
CREATE TABLE TRN_PERFILES(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESC_PERFIL VARCHAR(20) NOT NULL,
BACKEND TINYINT NOT NULL DEFAULT 0,
OBJETIVOS TINYINT NOT NULL DEFAULT 0,
SEGUIMIENTO TINYINT NOT NULL DEFAULT 0);